# basic options
title: Website's name
author: GitHub User
email: your-email@domain.com
description: This site is about...
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
