# basic options
title: Website's name
author: Emmanuel Castillo
email: Emm.CastilloG@gmail.com
description: This site is about...
#twitter_username: iEmmCastillo_
github_username:  forcesk

# Build settings
markdown: kramdown
theme: minima
