# basic options
title: Website's name
author: Emmanuel Castillo
email: Emm.CastilloG@gmail.com
description: This site is about...
#twitter_username: iEmmCastillo_
github_username:  forcesk
facebook_username: jekyll

# Build settings
markdown: kramdown
theme: minima

header_pages:
  - about.md
    - testing.md
  - home.md
